#!/usr/bin/env bash                                                                                               
#comment
x=0
while (( x < 10 ))
do
    echo Holberton School
    if (( x == 3 ))
    then
       echo bad luck
    fi
    if (( x == 8 ))
    then
	echo good luck
    fi
((x++))
done
