#!/usr/bin/env bash                                                                                               
#comment
x=0
while (( x < 10 ))
do
    echo Holberton School
    if (( x == 2 ))
    then
       echo bad luck
    fi
    if (( x == 7 ))
    then
	echo good luck
    fi
((x++))
done
